config/routes.rb
Rails.application.routes.draw do
  root 'channels#index'
  get '/users/addUser', to: 'users#addUser'
  get '/channels/createChannel', to: 'channels#createChannel'
  get '/piconets/createPiconet', to: 'piconets#createPiconet'
  get '/users/join', to: 'users#join'
  get'/users/leavePiconet', to: 'users#leavePiconet'
  get'/messages/sendMessage', to: 'messages#sendMessage'
  get '/messages/forward', to: 'messages#forwa'
  resources :users
  resources :u_sers
  resources :piconets
  resources :messages
  resources :channels
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/piconet.rb
class Piconet < ApplicationRecord
  belongs_to :channel

  has_many :users
  has_many :messages
end

app/controllers/piconets_controller.rb
class PiconetsController < ApplicationController
  before_action :set_piconet, only: [:show, :edit, :update, :destroy]

  # GET /piconets
  # GET /piconets.json
  def index
    @piconets = Piconet.all
    render json: @piconets, include: [:users]

  end


  # user id / piconet id

  # GET /piconets/1
  # GET /piconets/1.json
  def show
  end

  # GET /piconets/new
  def new
      @piconet = Piconet.new
  end

  # GET /piconets/1/edit
  def edit
  end

  # GET /piconets
  # GET /piconets.json
  #params= channelid = &master_id(phone_number)&numberofusers
  def createPiconet
    user = User.find_by(:phone_number => params[:master_id])
    @piconet = Piconet.new(:channel_id => params[:channel_id], :master_id => user[:id],:number_of_users => params[:number_of_users])
    @piconet.save
    channel = Channel.find_by(:id => params[:channel_id])
    channel[:piconet_id] = @piconet[:id]
    channel[:piconet_id] = @piconet[:id]
    channel.save
    user[:piconet_id] = @piconet[:id]
    user.save
  end

  def create
    if User.exists?(id: piconet_params[:master_id])
      @piconet = Piconet.new(piconet_params)
      respond_to do |format|
        if @piconet.save
          format.html { redirect_to @piconet, notice: 'Piconet was successfully created.' }
          format.json { render :show, status: :created, location: @piconet }
        else
          format.html { render :new }
          format.json { render json: @piconet.errors, status: :unprocessable_entity }
        end
      end
    else
       render json: {"errors": "Master should be a user", "errors": piconet_params[:master_id]}
    end
  end

  # PATCH/PUT /piconets/1
  # PATCH/PUT /piconets/1.json
  def update
    respond_to do |format|
      if @piconet.update(piconet_params)
        format.html { redirect_to @piconet, notice: 'Piconet was successfully updated.' }
        format.json { render :show, status: :ok, location: @piconet }
      else
        format.html { render :edit }
        format.json { render json: @piconet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piconets/1
  # DELETE /piconets/1.json
  def destroy
    @piconet.destroy
    respond_to do |format|
      format.html { redirect_to piconets_url, notice: 'Piconet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piconet
      @piconet = Piconet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piconet_params
      params.require(:piconet).permit(:channel_id, :master_id, )
    end
end

app/helpers/piconets_helper.rb
module PiconetsHelper
end

app/views/piconets/_form.html.erb
<%= form_with(model: piconet, local: true) do |form| %>
  <% if piconet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(piconet.errors.count, "error") %> prohibited this piconet from being saved:</h2>

      <ul>
      <% piconet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.number_field :channel_id, id: :piconet_channel_id %>
  </div>

  <div class="field">
    <%= form.label :master_id %>
    <%= form.number_field :master_id, id: :piconet_master_id %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/piconets/edit.html.erb
<h1>Editing Piconet</h1>

<%= render 'form', piconet: @piconet %>

<%= link_to 'Show', @piconet %> |
<%= link_to 'Back', piconets_path %>

app/views/piconets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Piconets</h1>

<table>
  <thead>
    <tr>
      <th>Channel</th>
      <th>Master</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @piconets.each do |piconet| %>
      <tr>
        <td><%= piconet.channel_id %></td>
        <td><%= piconet.master_id %></td>
        <td><%= link_to 'Show', piconet %></td>
        <td><%= link_to 'Edit', edit_piconet_path(piconet) %></td>
        <td><%= link_to 'Destroy', piconet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Piconet', new_piconet_path %>

app/views/piconets/new.html.erb
<h1>New Piconet</h1>

<%= render 'form', piconet: @piconet %>

<%= link_to 'Back', piconets_path %>

app/views/piconets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @piconet.channel_id %>
</p>

<p>
  <strong>Master:</strong>
  <%= @piconet.master_id %>
</p>




<%= link_to 'Edit', edit_piconet_path(@piconet) %> |
<%= link_to 'Back', piconets_path %>